"""Column Formula Constraint."""

from importlib import import_module

import pandas as pd

from sdmetrics.multi_table.statistical.constraints.base import BaseConstraint
from sdmetrics.multi_table.statistical.constraints.error import ConstraintNotApplicableError
from sdmetrics.multi_table.statistical.constraints.utils import (
    _format_invalid_values_string,
    _is_list_of_type,
)


class ColumnFormula(BaseConstraint):
    """constraint for columns derived by applying a function to other columns.

    Args:
        input_column_names (list[str]):
            The list of column names to pass into the formula function.
        output_column_name (str):
            The name of the column generated by the formula function.
        module_name (str, optional):
            The module path containing the formula function. Defaults to ``'__main__'``.
        formula_function_name (str):
            The name of the formula function. The function must accept a ``pd.DataFrame`` with
            the input columns and return a ``pd.Series`` for the output column.
        table_name (str, optional):
            The name of the table containing the input and output columns. Defaults to None for
            single table metadata.
    """

    def _get_formula_function(self, module_name, formula_function_name):
        """Import the formula function from its module."""
        try:
            formula_module = import_module(module_name)
        except ModuleNotFoundError as error:
            raise ValueError(f"Unable to import module '{module_name}'.") from error

        try:
            formula_function = getattr(formula_module, formula_function_name)
        except AttributeError as error:
            raise ValueError(
                f"Module '{module_name}' does not contain a function named "
                f"'{formula_function_name}'."
            ) from error

        if not callable(formula_function):
            raise TypeError(
                f'`formula_function_name` must reference a callable function. '
                f"'{formula_function_name}' is not callable."
            )

        return formula_function

    def __init__(
        self,
        input_column_names,
        output_column_name,
        formula_function_name,
        module_name='__main__',
        table_name=None,
    ):
        super().__init__()

        if not isinstance(table_name, str):
            raise ValueError("The 'table_name' parameter must be a string.")

        if not _is_list_of_type(input_column_names, str) or not input_column_names:
            raise ValueError(
                "The 'input_column_names' parameter must be a non-empty list of strings."
            )

        if not isinstance(output_column_name, str):
            raise ValueError("The 'output_column_name' parameter must be a string.")

        if not isinstance(formula_function_name, str):
            raise ValueError("The 'formula_function_name' parameter must be a string.")

        if not isinstance(module_name, str):
            raise ValueError("The 'module_name' parameter must be a string.")

        self.input_column_names = input_column_names
        self.output_column_name = output_column_name
        self.formula_function_name = formula_function_name
        self.module_name = module_name
        self.table_name = table_name

        self._formula_function = self._get_formula_function(module_name, formula_function_name)

    def _validate_data(self, data, metadata=None):
        """Check that the table, the columns and the formula function are all available."""
        if self.table_name not in data:
            raise ConstraintNotApplicableError(
                f"The table '{self.table_name}' is missing from the data."
            )

        columns = data[self.table_name].columns
        formula_columns = [*self.input_column_names, self.output_column_name]
        missing_columns = [
            column_name for column_name in formula_columns if column_name not in columns
        ]
        if missing_columns:
            missing_columns = "', '".join(missing_columns)
            raise ConstraintNotApplicableError(
                f"The column(s) '{missing_columns}' are missing from the table '{self.table_name}'."
            )

    def _get_formula_output(self, data):
        missing_columns = set(self.input_column_names) - set(data.columns)
        if missing_columns:
            missing_columns = _format_invalid_values_string(missing_columns, 5)
            raise ConstraintNotApplicableError(
                f'Data is missing input columns {missing_columns} for the formula.'
            )

        formula_output = self._formula_function(data[self.input_column_names])
        if not isinstance(formula_output, pd.Series):
            raise TypeError('The formula function must return a pandas Series.')

        return formula_output

    def _get_valid_rows(self, data):
        formula_output = self._get_formula_output(data)
        if self.output_column_name not in data.columns:
            raise ConstraintNotApplicableError(
                f"Data is missing output column '{self.output_column_name}' for the formula."
            )

        output_column = data[self.output_column_name]
        valid_rows = formula_output.eq(output_column) | (
            formula_output.isna() & output_column.isna()
        )
        return valid_rows.fillna(False)

    def _is_valid(self, data, metadata=None):
        """Return row-level validity based on the formula output."""
        table_name = self._get_single_table_name(metadata)
        is_valid = {table: pd.Series(True, index=data[table].index) for table in data}
        is_valid[table_name] = self._get_valid_rows(data[table_name])
        return is_valid
