{% set name = 'sdmetrics' %}
{% set version = '0.2.0.dev0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6,<3.9
    - scikit-learn >=0.23,<1
    - scipy >=1.4.1,<2
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pomegranate >=0.13.4,<0.14.2
    - pytorch >=1.4,<2
    - sktime >=0.4,<0.6
    - rdt >=0.2.10,<0.5

  run:
    - python >=3.6,<3.9
    - scikit-learn >=0.23,<1
    - scipy >=1.4.1,<2
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pomegranate >=0.13.4,<0.14.2
    - pytorch >=1.4,<2
    - sktime >=0.4,<0.6
    - rdt >=0.2.10,<0.5

about:
  home: "https://github.com/sdv-dev/SDMetrics"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Metrics for Synthetic Data Generation Projects"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
